"""Phase 6D Task D: Peak section -- top-1000 individual 1Y/3Y/5Y PEAK3 peaks.

Read-only. Serves data/game/experimental/player_pool_1500/top_1000_peaks.v1.json
(generated by scripts/build_top_peaks.py from the SAME official peak3.py
formula the canonical leaderboards use, just against a broader universe than
the 250-pool -- see that script's own module docstring). This module
computes/derives nothing at request time; no PEAK3 score is ever calculated
here (CLAUDE.md: never calculate PEAK3 scores outside the Python model).

Deliberately separate from /api/v1/leaderboards (the canonical 250-pool
route) -- this is an experimental, broader-population surface, and must stay
labeled as such rather than presented as replacing the canonical rankings.

Two routes, on purpose (identical split to /api/v1/seasons):
  GET /peaks?window=1y|3y|5y     -> lean rows for the ranked table
  GET /peaks/{row_id}/explain    -> the heavy per-window breakdown
Before Phase 9C this board published NO component data at all, so the
explainability modal rendered "Not available for this view" for the entire
breakdown even though nba_peak.leaderboards.build_leaderboard had already
computed every official contribution. The generator now carries them through;
the explain blocks are ~18 MB in aggregate and are therefore served only by the
per-row route, never with the table.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Optional

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

_repo_root = Path(__file__).resolve().parent.parent.parent.parent.parent.parent
if str(_repo_root) not in sys.path:
    sys.path.insert(0, str(_repo_root))

from app.core.config import settings  # noqa: E402
from nba_peak.perfect_season.assets import get_player_headshot_url  # noqa: E402

router = APIRouter()

DATA_PATH = _repo_root / "data" / "game" / "experimental" / "player_pool_1500" / "top_1000_peaks.v1.json"
VALID_WINDOWS = {"1y", "3y", "5y"}

_CACHE: Optional[dict] = None


def _load() -> dict:
    global _CACHE
    if _CACHE is None:
        if not DATA_PATH.exists():
            raise HTTPException(
                status_code=503,
                detail={
                    "error_code": "peaks_data_unavailable",
                    "message": f"{DATA_PATH.name} not generated -- run scripts/build_top_peaks.py",
                },
            )
        _CACHE = json.loads(DATA_PATH.read_text())
    return _CACHE


class PeakRow(BaseModel):
    rank: int
    player_slug: str
    player_name: str
    window_label: str
    anchor_season: str
    team: Optional[str] = None
    prime_score: float
    data_completeness: str
    # Phase 9B: the anchor season's real minutes per game. The generator
    # (scripts/build_top_peaks.py) only publishes windows whose anchor season
    # clears MIN_SERVED_ANCHOR_MPG, and it writes this field so the value is
    # inspectable rather than an invisible precondition -- without declaring it
    # here Pydantic silently dropped it, leaving the explainability modal to
    # state the gate as a generic footnote instead of showing the row's actual
    # minutes. Optional because an older generated artifact won't carry it.
    anchor_season_mpg: Optional[float] = None
    # ------------------------------------------------------------------ 9C ---
    # The shared two-board rankings contract. Every field is Optional with a
    # default so an OLDER generated artifact (one built before
    # scripts/build_top_peaks.py started carrying these through) still
    # validates and simply renders as "not available" rather than 500ing.
    #
    # `row_id` keys the explain route; `label` is the human window span
    # ("1988-89 to 1990-91") next to the generator's compact `window_label`.
    row_id: Optional[str] = None
    label: Optional[str] = None
    window: Optional[str] = None
    mpg: Optional[float] = None
    prime_index: Optional[float] = None
    # The five OFFICIAL weighted contributions, straight from
    # build_leaderboard's own decomposition -- the thing this board used to drop
    # on the floor. Nothing is computed here.
    components: Optional[dict[str, Optional[float]]] = None
    # 0-100 rank of each contribution, plus the total, within this duration's
    # served population. A rank of official numbers, never a new score.
    percentiles: Optional[dict[str, Optional[float]]] = None
    season_in_progress: bool = False
    # Phase 6E Part B: asset-manifest schema readiness -- always None today.
    headshot_url: Optional[str] = None


class PeaksResponse(BaseModel):
    window: str
    duration_years: int
    dataset_version: str
    formula_version: str
    supported_start_season: str
    supported_end_season: str
    universe_identity_count: int
    total_available: int
    # Surfaced so the UI can state the minutes floor as a caveat rather than
    # implying the board is unfiltered. Optional: an older artifact lacks them.
    min_anchor_season_mpg: Optional[float] = None
    excluded_low_minute_windows: Optional[int] = None
    serving_gate_note: Optional[str] = None
    rows: list[PeakRow]


class PeakExplainResponse(BaseModel):
    """Intentionally loose, exactly like SeasonExplainResponse: the explain block
    is a nested, evolving diagnostic payload generated from real parquet columns
    and from build_leaderboard's own component decomposition, and pinning every
    nested field here would mean re-typing model internals in the API layer. The
    route's contract is "the generated explain block for this row_id, verbatim"
    -- the frontend renders only the fields it recognises and shows "not
    available" for anything absent rather than substituting a value."""

    row_id: str
    explain: dict[str, Any]


@router.get("/peaks", response_model=PeaksResponse)
async def get_peaks(
    window: str = Query(..., description="1y | 3y | 5y"),
    limit: int = Query(default=1000, ge=1, le=1000),
    search: str = Query(default=""),
) -> PeaksResponse:
    if window not in VALID_WINDOWS:
        raise HTTPException(status_code=422, detail=f"window must be one of {sorted(VALID_WINDOWS)}, got '{window}'")

    data = _load()
    bucket = data["windows"][window]
    rows = bucket["rows"]
    if search:
        q = search.lower()
        rows = [r for r in rows if q in r["player_name"].lower()]
    total_available = len(rows)
    rows = rows[:limit]

    # Phase 6F Part C: real headshot URLs only behind the explicit,
    # default-off flag -- see nba_peak.perfect_season.assets module
    # docstring for the "metadata only, no license grant yet" caveat.
    if settings.ENABLE_EXTERNAL_ASSET_URLS:
        enriched_rows = []
        for r in rows:
            r = dict(r)
            r["headshot_url"] = get_player_headshot_url(r["player_slug"])
            enriched_rows.append(r)
        rows = enriched_rows

    return PeaksResponse(
        window=window,
        duration_years=bucket["duration_years"],
        dataset_version=data["dataset_version"],
        formula_version=data["formula_version"],
        supported_start_season=data["supported_start_season"],
        supported_end_season=data["supported_end_season"],
        universe_identity_count=data["universe_identity_count"],
        total_available=total_available,
        min_anchor_season_mpg=bucket.get("min_anchor_season_mpg"),
        excluded_low_minute_windows=bucket.get("excluded_low_minute_windows"),
        serving_gate_note=data.get("serving_gate_note"),
        rows=[PeakRow(**r) for r in rows],
    )


@router.get("/peaks/{row_id}/explain", response_model=PeakExplainResponse)
async def get_peak_explain(row_id: str) -> PeakExplainResponse:
    """The per-row breakdown, fetched on modal open rather than shipped with the
    table. Keyed by row_id ({player_slug}-{n}yr-{anchor_season}), which embeds
    the duration, so ONE route serves the 1Y, 3Y and 5Y boards and a comparison
    entry can pivot the modal across durations."""
    data = _load()
    block = (data.get("explain") or {}).get(row_id)
    if block is None:
        raise HTTPException(
            status_code=404,
            detail={
                "error_code": "peak_row_not_found",
                "message": f"No served peak window with id '{row_id}'",
            },
        )
    return PeakExplainResponse(row_id=row_id, explain=block)
