"""Phase 6D Task D: Peak section -- top-1000 individual 1Y/3Y/5Y PEAK3 peaks.

Read-only. Serves data/game/experimental/player_pool_1500/top_1000_peaks.v1.json
(generated by scripts/build_top_peaks.py from the SAME official peak3.py
formula the canonical leaderboards use, just against a broader universe than
the 250-pool -- see that script's own module docstring). This module
computes/derives nothing at request time; no PEAK3 score is ever calculated
here (CLAUDE.md: never calculate PEAK3 scores outside the Python model).

Deliberately separate from /api/v1/leaderboards (the canonical 250-pool
route) -- this is an experimental, broader-population surface, and must stay
labeled as such rather than presented as replacing the canonical rankings.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

_repo_root = Path(__file__).resolve().parent.parent.parent.parent.parent.parent
if str(_repo_root) not in sys.path:
    sys.path.insert(0, str(_repo_root))

router = APIRouter()

DATA_PATH = _repo_root / "data" / "game" / "experimental" / "player_pool_1500" / "top_1000_peaks.v1.json"
VALID_WINDOWS = {"1y", "3y", "5y"}

_CACHE: Optional[dict] = None


def _load() -> dict:
    global _CACHE
    if _CACHE is None:
        if not DATA_PATH.exists():
            raise HTTPException(
                status_code=503,
                detail={
                    "error_code": "peaks_data_unavailable",
                    "message": f"{DATA_PATH.name} not generated -- run scripts/build_top_peaks.py",
                },
            )
        _CACHE = json.loads(DATA_PATH.read_text())
    return _CACHE


class PeakRow(BaseModel):
    rank: int
    player_slug: str
    player_name: str
    window_label: str
    anchor_season: str
    team: Optional[str] = None
    prime_score: float
    data_completeness: str


class PeaksResponse(BaseModel):
    window: str
    duration_years: int
    dataset_version: str
    formula_version: str
    supported_start_season: str
    supported_end_season: str
    universe_identity_count: int
    total_available: int
    rows: list[PeakRow]


@router.get("/peaks", response_model=PeaksResponse)
async def get_peaks(
    window: str = Query(..., description="1y | 3y | 5y"),
    limit: int = Query(default=1000, ge=1, le=1000),
    search: str = Query(default=""),
) -> PeaksResponse:
    if window not in VALID_WINDOWS:
        raise HTTPException(status_code=422, detail=f"window must be one of {sorted(VALID_WINDOWS)}, got '{window}'")

    data = _load()
    bucket = data["windows"][window]
    rows = bucket["rows"]
    if search:
        q = search.lower()
        rows = [r for r in rows if q in r["player_name"].lower()]
    total_available = len(rows)
    rows = rows[:limit]

    return PeaksResponse(
        window=window,
        duration_years=bucket["duration_years"],
        dataset_version=data["dataset_version"],
        formula_version=data["formula_version"],
        supported_start_season=data["supported_start_season"],
        supported_end_season=data["supported_end_season"],
        universe_identity_count=data["universe_identity_count"],
        total_available=total_available,
        rows=[PeakRow(**r) for r in rows],
    )
