"""Phase 6D Task D: Peak section -- top-1000 individual 1Y/3Y/5Y PEAK3 peaks.

Read-only. Serves data/game/experimental/player_pool_1500/top_1000_peaks.v1.json
(generated by scripts/build_top_peaks.py from the SAME official peak3.py
formula the canonical leaderboards use, just against a broader universe than
the 250-pool -- see that script's own module docstring). This module
computes/derives nothing at request time; no PEAK3 score is ever calculated
here (CLAUDE.md: never calculate PEAK3 scores outside the Python model).

Deliberately separate from /api/v1/leaderboards (the canonical 250-pool
route) -- this is an experimental, broader-population surface, and must stay
labeled as such rather than presented as replacing the canonical rankings.

Two routes, on purpose (identical split to /api/v1/seasons):
  GET /peaks?window=1y|2y|3y|5y  -> lean rows for the ranked table
  GET /peaks/{row_id}/explain    -> the heavy per-window breakdown
Before Phase 9C this board published NO component data at all, so the
explainability modal rendered "Not available for this view" for the entire
breakdown even though nba_peak.leaderboards.build_leaderboard had already
computed every official contribution. The generator now carries them through;
the explain blocks are ~18 MB in aggregate and are therefore served only by the
per-row route, never with the table.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path
from typing import Any, Optional

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

_repo_root = Path(__file__).resolve().parent.parent.parent.parent.parent.parent
if str(_repo_root) not in sys.path:
    sys.path.insert(0, str(_repo_root))

from app.core.config import settings  # noqa: E402
from nba_peak import formula_version  # noqa: E402
from nba_peak.perfect_season.assets import get_player_headshot_url  # noqa: E402

router = APIRouter()

_DATA_DIR = _repo_root / "data" / "game" / "experimental" / "player_pool_1500"
# One artifact per scoring model. v1 remains the DEFAULT; v2 is served only when
# a caller asks for it by name, so no existing client silently changes model
# version (docs/model/PEAK3_V2_FORMULA_DESIGN.md section 7).
_DATA_PATHS = {
    formula_version.PEAK3_V1: _DATA_DIR / "top_1000_peaks.v1.json",
    formula_version.PEAK3_V2: _DATA_DIR / "top_1000_peaks.v2.json",
}
DATA_PATH = _DATA_PATHS[formula_version.PEAK3_V1]
# 2y is a first-class canonical window, not an interpolation between 1y and 3y:
# it comes from leaderboards/top_250_2_year_prime.csv, which peak3.n_year_windows
# generates with n=2 through exactly the same weighted-window machinery as 3 and
# 5. The exporter has always emitted it (build_web_dataset.CSV_FILES) and
# metadata.supported_durations has always listed it -- this validator was the
# only thing rejecting it, so the data was served-ready and unreachable.
VALID_WINDOWS = {"1y", "2y", "3y", "5y"}

# Process-lifetime, keyed by formula version, populated once and never
# invalidated or mtime-checked. That is deliberate (the artifacts are committed
# and immutable per release) but it IS a staleness vector: regenerating
# top_1000_peaks.v1.json does not reach a running server until the process
# restarts. `_DIGEST_CACHE` below makes that condition detectable instead of
# invisible -- the digest published in the response is the digest of the bytes
# THIS process loaded, so a client (or a parity test) can compare it against the
# file on disk and see the divergence rather than having to infer it.
_CACHE: dict[str, dict] = {}
_DIGEST_CACHE: dict[str, str] = {}


def _artifact_digest(version: str) -> Optional[str]:
    """SHA-256 of the artifact bytes THIS process is actually serving.

    Deliberately reads only `_DIGEST_CACHE`, which `_load` populates from the
    exact string it parsed. Re-opening the file here would defeat the point:
    `_CACHE` is never invalidated, so after a regeneration the process keeps
    serving the OLD rows while a fresh read of the path returns the NEW digest.
    The response would then publish a fingerprint that matches disk while the
    body does not -- the one failure mode this value exists to make visible,
    reported as "current". Returns None until the board has been loaded once.
    """
    return _DIGEST_CACHE.get(version)


def _resolve_version(value: Optional[str]) -> str:
    try:
        return formula_version.normalize(value)
    except ValueError:
        raise HTTPException(
            status_code=422,
            detail={
                "error_code": "unknown_model_version",
                "message": (f"model_version must be one of "
                            f"{list(formula_version.ALL_FORMULA_VERSIONS)}, got {value!r}"),
            },
        )


def _load(version: Optional[str] = None) -> dict:
    """The served board for one model version, cached per version."""
    resolved = _resolve_version(version)
    cached = _CACHE.get(resolved)
    if cached is None:
        path = _DATA_PATHS[resolved]
        if not path.exists():
            raise HTTPException(
                status_code=503,
                detail={
                    "error_code": "peaks_data_unavailable",
                    "message": (f"{path.name} not generated -- run "
                                f"scripts/build_top_peaks.py --formula-version {resolved}"),
                },
            )
        raw = path.read_text()
        # Digest the bytes we are about to serve, in the same breath as reading
        # them, so the fingerprint can never describe a different revision of
        # the file than `_CACHE` holds. See `_artifact_digest`.
        _DIGEST_CACHE[resolved] = hashlib.sha256(raw.encode("utf-8")).hexdigest()
        cached = _CACHE[resolved] = json.loads(raw)
    return cached


class PeakRow(BaseModel):
    rank: int
    player_slug: str
    player_name: str
    window_label: str
    anchor_season: str
    team: Optional[str] = None
    prime_score: float
    data_completeness: str
    # Phase 9B: the anchor season's real minutes per game. The generator
    # (scripts/build_top_peaks.py) only publishes windows whose anchor season
    # clears MIN_SERVED_ANCHOR_MPG, and it writes this field so the value is
    # inspectable rather than an invisible precondition -- without declaring it
    # here Pydantic silently dropped it, leaving the explainability modal to
    # state the gate as a generic footnote instead of showing the row's actual
    # minutes. Optional because an older generated artifact won't carry it.
    anchor_season_mpg: Optional[float] = None
    # ------------------------------------------------------------------ 9C ---
    # The shared two-board rankings contract. Every field is Optional with a
    # default so an OLDER generated artifact (one built before
    # scripts/build_top_peaks.py started carrying these through) still
    # validates and simply renders as "not available" rather than 500ing.
    #
    # `row_id` keys the explain route; `label` is the human window span
    # ("1988-89 to 1990-91") next to the generator's compact `window_label`.
    row_id: Optional[str] = None
    label: Optional[str] = None
    window: Optional[str] = None
    mpg: Optional[float] = None
    prime_index: Optional[float] = None
    # The five OFFICIAL weighted contributions, straight from
    # build_leaderboard's own decomposition -- the thing this board used to drop
    # on the floor. Nothing is computed here.
    components: Optional[dict[str, Optional[float]]] = None
    # 0-100 rank of each contribution, plus the total, within this duration's
    # served population. A rank of official numbers, never a new score.
    percentiles: Optional[dict[str, Optional[float]]] = None
    season_in_progress: bool = False
    # Which scoring model produced this row. Optional so an artifact generated
    # before versioning still validates; the response-level field always
    # resolves, so the UI never has to guess.
    model_version: Optional[str] = None
    # Phase 6E Part B: asset-manifest schema readiness -- always None today.
    headshot_url: Optional[str] = None


class PeaksResponse(BaseModel):
    window: str
    duration_years: int
    dataset_version: str
    formula_version: str
    # The scoring model these rows come from, and whether it is the default one.
    # Both are always present so a client can label the board without having to
    # parse `formula_version`'s prose.
    model_version: str
    model_label: str
    is_default_model: bool
    supported_start_season: str
    supported_end_season: str
    universe_identity_count: int
    total_available: int
    # Surfaced so the UI can state the minutes floor as a caveat rather than
    # implying the board is unfiltered. Optional: an older artifact lacks them.
    min_anchor_season_mpg: Optional[float] = None
    excluded_low_minute_windows: Optional[int] = None
    serving_gate_note: Optional[str] = None
    # ------------------------------------------------------- provenance (W6) ---
    # Additive. Nothing below is derived from a score; these describe WHICH bytes
    # produced the rows above, so "is this board current?" is an answerable
    # question rather than an inference from file mtimes (which are a checkout
    # artifact and were the original cause of a false staleness report).
    #
    # `artifact_digest` is the SHA-256 of the artifact THIS process loaded. Since
    # `_CACHE` is never invalidated, comparing it to the file on disk is the only
    # reliable way to detect a server serving a superseded board.
    artifact_digest: Optional[str] = None
    # Pass-through. The generator does not yet write a `generated_at` into
    # top_1000_peaks.v*.json, so this is None today rather than being
    # back-filled from a file mtime -- an mtime would be a fabricated release
    # date, and fabricating provenance is the exact defect this pass fixes. When
    # scripts/build_top_peaks.py starts emitting it, it flows through unchanged.
    generated_at: Optional[str] = None
    # How to reproduce this artifact, verbatim from the artifact itself.
    generation_command: Optional[str] = None
    rows: list[PeakRow]


class PeakExplainResponse(BaseModel):
    """Intentionally loose, exactly like SeasonExplainResponse: the explain block
    is a nested, evolving diagnostic payload generated from real parquet columns
    and from build_leaderboard's own component decomposition, and pinning every
    nested field here would mean re-typing model internals in the API layer. The
    route's contract is "the generated explain block for this row_id, verbatim"
    -- the frontend renders only the fields it recognises and shows "not
    available" for anything absent rather than substituting a value."""

    row_id: str
    explain: dict[str, Any]


@router.get("/peaks", response_model=PeaksResponse)
async def get_peaks(
    window: str = Query(..., description="1y | 2y | 3y | 5y"),
    limit: int = Query(default=1000, ge=1, le=1000),
    search: str = Query(default=""),
    model_version: Optional[str] = Query(
        default=None,
        description="peak3_v1 (default) | peak3_v2 (preview)"),
) -> PeaksResponse:
    if window not in VALID_WINDOWS:
        raise HTTPException(status_code=422, detail=f"window must be one of {sorted(VALID_WINDOWS)}, got '{window}'")

    version = _resolve_version(model_version)
    data = _load(version)
    bucket = data["windows"][window]
    rows = bucket["rows"]
    if search:
        q = search.lower()
        rows = [r for r in rows if q in r["player_name"].lower()]
    total_available = len(rows)
    rows = rows[:limit]

    # Phase 6F Part C: real headshot URLs only behind the explicit,
    # default-off flag -- see nba_peak.perfect_season.assets module
    # docstring for the "metadata only, no license grant yet" caveat.
    if settings.ENABLE_EXTERNAL_ASSET_URLS:
        enriched_rows = []
        for r in rows:
            r = dict(r)
            r["headshot_url"] = get_player_headshot_url(r["player_slug"])
            enriched_rows.append(r)
        rows = enriched_rows

    return PeaksResponse(
        window=window,
        duration_years=bucket["duration_years"],
        dataset_version=data["dataset_version"],
        formula_version=data["formula_version"],
        model_version=version,
        model_label=formula_version.label(version),
        is_default_model=formula_version.is_default(version),
        supported_start_season=data["supported_start_season"],
        supported_end_season=data["supported_end_season"],
        universe_identity_count=data["universe_identity_count"],
        total_available=total_available,
        min_anchor_season_mpg=bucket.get("min_anchor_season_mpg"),
        excluded_low_minute_windows=bucket.get("excluded_low_minute_windows"),
        serving_gate_note=data.get("serving_gate_note"),
        artifact_digest=_artifact_digest(version),
        generated_at=data.get("generated_at"),
        generation_command=data.get("generation_command"),
        rows=[PeakRow(**r) for r in rows],
    )


@router.get("/peaks/{row_id}/explain", response_model=PeakExplainResponse)
async def get_peak_explain(
    row_id: str,
    model_version: Optional[str] = Query(
        default=None,
        description="peak3_v1 (default) | peak3_v2 (preview)"),
) -> PeakExplainResponse:
    """The per-row breakdown, fetched on modal open rather than shipped with the
    table. Keyed by row_id ({player_slug}-{n}yr-{anchor_season}), which embeds
    the duration, so ONE route serves the 1Y, 3Y and 5Y boards and a comparison
    entry can pivot the modal across durations."""
    version = _resolve_version(model_version)
    data = _load(version)
    block = (data.get("explain") or {}).get(row_id)
    if block is None:
        raise HTTPException(
            status_code=404,
            detail={
                "error_code": "peak_row_not_found",
                "message": f"No served peak window with id '{row_id}'",
            },
        )
    # Stamp the version on the block so a modal opened from a v2 board cannot
    # display v2 numbers under a v1 label if the artifact predates versioning.
    block = {**block, "model_version": version}
    return PeakExplainResponse(row_id=row_id, explain=block)
