"""Phase 9B: Single Seasons board -- top-1000 individual PEAK3 seasons.

Read-only. Serves
data/game/experimental/player_pool_1500/top_1000_seasons.v1.json (generated by
scripts/build_top_seasons.py, which is a pure sort/projection of the official
per-season prime_raw/prime_score and weighted component contributions already
stored in cache/processed/scored_1980_2026.parquet). This module
computes/derives nothing at request time and never calculates a PEAK3 score
(CLAUDE.md: never calculate PEAK3 scores outside the Python model).

Deliberately a THIRD surface, separate from both /api/v1/leaderboards (the
canonical 250-pool board) and /api/v1/peaks (best window per player across a
broader universe). Those two are one-row-per-player by construction; this one
is one row per SEASON, so a player can legitimately appear many times. That is
the entire point of the board and must never be "deduped" into parity with the
other two.

Two routes, on purpose:
  GET /seasons                      -> lean rows for the ranked table
  GET /seasons/{season_id}/explain  -> the heavy per-season breakdown
The explain blocks are ~3.4 MB in aggregate; shipping them with the table would
make the rankings page pay for a modal most visitors never open, so the modal
fetches its own row on open.

Serving gate: rows in the generated artifact have already been filtered to
seasons of >= 25.0 MPG (see scripts/build_top_seasons.py::MIN_SERVED_SEASON_MPG
for the audit that motivated it). This module does not re-filter -- it surfaces
the floor in the response so the UI can state it as a caveat rather than
implying the board is unfiltered.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Optional

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

_repo_root = Path(__file__).resolve().parent.parent.parent.parent.parent.parent
if str(_repo_root) not in sys.path:
    sys.path.insert(0, str(_repo_root))

router = APIRouter()

DATA_PATH = (
    _repo_root / "data" / "game" / "experimental" / "player_pool_1500" / "top_1000_seasons.v1.json"
)

_CACHE: Optional[dict] = None


def _load() -> dict:
    global _CACHE
    if _CACHE is None:
        if not DATA_PATH.exists():
            raise HTTPException(
                status_code=503,
                detail={
                    "error_code": "seasons_data_unavailable",
                    "message": (
                        f"{DATA_PATH.name} not generated -- run scripts/build_top_seasons.py"
                    ),
                },
            )
        _CACHE = json.loads(DATA_PATH.read_text())
    return _CACHE


class SeasonRow(BaseModel):
    rank: int
    season_id: str
    player_slug: str
    player_name: str
    season: str
    team: Optional[str] = None
    is_multi_team_season: bool = False
    prime_score: Optional[float] = None
    prime_index: Optional[float] = None
    # Present on every served row so the minutes floor is verifiable per row,
    # not just asserted by a summary field.
    season_mpg: Optional[float] = None
    season_in_progress: bool = False
    # ------------------------------------------------------------------ 9C ---
    # The shared two-board rankings contract, so one frontend normalizer reads a
    # row from this board and from /api/v1/peaks identically. Every field is
    # Optional with a default: an OLDER generated artifact still validates and
    # simply renders as "not available" rather than 500ing.
    #
    # `row_id` is the SAME value as `season_id` (both key the explain route);
    # `season_id` is kept because existing clients read it.
    row_id: Optional[str] = None
    label: Optional[str] = None
    mpg: Optional[float] = None
    # The five OFFICIAL weighted contributions and the 0-100 rank of each (plus
    # of the total) within this board's served population. Both are projections
    # of already-official values; no score is computed here.
    components: Optional[dict[str, Optional[float]]] = None
    percentiles: Optional[dict[str, Optional[float]]] = None
    data_completeness: Optional[str] = None


class SeasonsResponse(BaseModel):
    dataset_version: str
    formula_version: str
    supported_start_season: str
    supported_end_season: str
    universe_identity_count: int
    total_scored_seasons: int
    allows_repeated_players: bool
    min_season_mpg: float
    excluded_low_minute_seasons: int
    serving_gate_note: str
    effective_tie_threshold: float
    total_available: int
    offset: int
    limit: int
    rows: list[SeasonRow]


class SeasonExplainResponse(BaseModel):
    """Intentionally loose: the explain block is a nested, evolving diagnostic
    payload generated from real parquet columns, and pinning every nested field
    here would mean re-typing model internals in the API layer. The route's
    contract is "the generated explain block for this season_id, verbatim" --
    the frontend renders only the fields it recognises and shows "not available"
    for anything absent rather than substituting a value."""

    season_id: str
    # Same value as season_id, mirroring the row contract so a caller that only
    # knows about row_id never has to special-case this board.
    row_id: Optional[str] = None
    explain: dict[str, Any]


@router.get("/seasons", response_model=SeasonsResponse)
async def get_seasons(
    limit: int = Query(default=1000, ge=1, le=1000),
    offset: int = Query(default=0, ge=0),
    search: str = Query(default=""),
) -> SeasonsResponse:
    data = _load()
    rows = data["rows"]

    if search:
        q = search.lower()
        # Season text is searchable too ("1990-91") -- on a board where one
        # player holds many rows, filtering by season is as natural as by name.
        rows = [r for r in rows if q in r["player_name"].lower() or q in r["season"].lower()]

    total_available = len(rows)
    rows = rows[offset : offset + limit]

    return SeasonsResponse(
        dataset_version=data["dataset_version"],
        formula_version=data["formula_version"],
        supported_start_season=data["supported_start_season"],
        supported_end_season=data["supported_end_season"],
        universe_identity_count=data["universe_identity_count"],
        total_scored_seasons=data["total_scored_seasons"],
        allows_repeated_players=data["allows_repeated_players"],
        min_season_mpg=data["min_season_mpg"],
        excluded_low_minute_seasons=data["excluded_low_minute_seasons"],
        serving_gate_note=data["serving_gate_note"],
        effective_tie_threshold=data["effective_tie_threshold"],
        total_available=total_available,
        offset=offset,
        limit=limit,
        rows=[SeasonRow(**r) for r in rows],
    )


@router.get("/seasons/{season_id}/explain", response_model=SeasonExplainResponse)
async def get_season_explain(season_id: str) -> SeasonExplainResponse:
    """The per-row breakdown, fetched on modal open rather than shipped with the
    table. Includes the `comparisons` rails (same player's other seasons, nearest
    scores, same-season peers), each entry carrying a row_id so the modal can
    pivot straight onto it."""
    data = _load()
    block = data["explain"].get(season_id)
    if block is None:
        raise HTTPException(
            status_code=404,
            detail={
                "error_code": "season_not_found",
                "message": f"No served season with id '{season_id}'",
            },
        )
    return SeasonExplainResponse(season_id=season_id, row_id=season_id, explain=block)
