#!/usr/bin/env python3
"""Build the NBA Fact of the Day bank into `data/web/nba_facts.v1.json`.

OFFLINE, DETERMINISTIC, AND NO MODEL IS CALLED. Reads one committed JSON of
curated facts and one committed table of per-season rows, scores every
candidate, applies the quality gate and the duplicate check, and writes a sorted
bank. No network, no clock, no LLM — running it twice against unchanged inputs
produces a byte-identical file, which is what makes "the bank changed" mean "an
input changed".

    python scripts/build_nba_facts.py
    python scripts/build_nba_facts.py --report docs/implementation/NBA_FACT_BANK_REPORT.md

THE BUILD FAILS RATHER THAN SHIPS A DEGRADED BANK. An editorial entry with no
source, an unexpired fact about the present, a bank under `MIN_FACTS`, a
category nothing in the vocabulary knows — every one of these stops the build
and names the entry, because each is a way for a homepage to publish something
nobody checked.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from nba_peak.nba_facts import (  # noqa: E402
    BANK_PATH,
    CATEGORIES,
    EditorialFactError,
    MIN_FACTS,
    PERISHABLE_CATEGORIES,
    assert_inputs_present,
    bank_payload,
    build_bank,
    build_candidates,
    build_report,
)


def _markdown(report: dict) -> str:
    def table(title: str, mapping: dict, key_header: str) -> str:
        rows = "\n".join(f"| {k} | {v} |" for k, v in mapping.items())
        return f"### {title}\n\n| {key_header} | Facts |\n|---|---|\n{rows}\n"

    rotation = report["rotation"]
    repeat = report["repeat_window"]
    dist = report["distribution"]

    lines = [
        "# NBA Fact of the Day — bank generation report",
        "",
        "Generated by `scripts/build_nba_facts.py`. Every number below comes from",
        "the same run that produced the bank, so this file cannot describe a",
        "different one.",
        "",
        "## Totals",
        "",
        "| | |",
        "|---|---|",
        f"| Bank version | `{report['bank_version']}` |",
        f"| Published facts | **{report['total']}** |",
        f"| Candidates considered | {report['candidates']} |",
        f"| Rejected | {report['rejected']} |",
        f"| Duplicates and near-duplicates | {report['duplicates']} |",
        f"| Facts with an expiry | {len(report['perishable'])} |",
        "",
        "### Why candidates were rejected",
        "",
        "| Reason | Count |",
        "|---|---|",
    ]
    for reason, count in report["reject_reasons"].items():
        lines.append(f"| `{reason}` | {count} |")
    lines += [
        "",
        "Two of those are ceilings rather than quality judgements, and both are",
        "counted here precisely so they do not read as \"the generator only found",
        "twelve\":",
        "",
        "* **`pattern_cap`** — one generator is one template, and no template may",
        "  contribute more than twelve facts. A generator finds its pattern once",
        "  per player, so one pattern can produce hundreds that are individually",
        "  fine and collectively a survey.",
        "* **`group_cap`** — no rotation group may exceed a third of the bank. The",
        "  pattern cap binds one generator and not a FAMILY of them: five separate",
        "  streak generators plus the record and oddity patterns had put 51% of the",
        "  bank into one group, which `rotation.py` cannot alternate away from.",
        "",
        table("By provenance", report["by_provenance"], "Provenance"),
        table("By category", report["by_category"], "Category"),
        table("By era", report["by_era"], "Era"),
        table("By geography", report["by_geography"], "Geography"),
        "### Domestic, global and women's basketball",
        "",
        "| | Facts | Share |",
        "|---|---|---|",
        f"| NBA / domestic | {dist['nba_domestic']} | "
        f"{100 * dist['nba_domestic'] // max(report['total'], 1)}% |",
        f"| Global or international | {dist['global_or_international']} | "
        f"{100 * dist['global_or_international'] // max(report['total'], 1)}% |",
        f"| Women's basketball | {dist['womens_basketball']} | "
        f"{100 * dist['womens_basketball'] // max(report['total'], 1)}% |",
        "",
        "Counted separately on purpose: a WNBA fact is domestic and a EuroLeague",
        "fact is international, so one geography field cannot answer both.",
        "",
        "### Semantic coverage",
        "",
        "WHAT THE FACTS ARE ABOUT, which is a different question from the table",
        "above it. A fact carries one `category` — chosen by whichever generator",
        "or curator produced it — and can be about several things at once: \"The",
        "Dream Team exists because of a vote the United States lost\" is filed",
        "`olympics_fiba` and is equally foundational NBA history, a rule change,",
        "and a global-basketball fact. So these counts SUM TO MORE THAN THE BANK,",
        "deliberately, and a category counter reporting four women's-basketball",
        "facts for a bank that has ten is answering a question nobody asked.",
        "",
        "Classification is `nba_peak/nba_facts/coverage.py`: a fact joins an area",
        "through its category, or through a narrow lexicon of proper nouns and",
        "terms of art it actually names, or through a structured field. The",
        "lexicons are deliberately narrow — a generous matcher would make",
        "coverage look solved by definition, which is the failure mode a coverage",
        "target invites.",
        "",
        "| Area | Facts | Target |",
        "|---|---|---|",
    ]
    for entry in report["semantic_coverage"]:
        target = entry["target"]
        met = "" if target is None else (" ✓" if entry["count"] >= target else " ✗")
        lines.append(
            f"| {entry['label']} | {entry['count']} | "
            f"{'—' if target is None else target}{met} |"
        )
    lines += [
        "",
        "Targets are the product brief's preferred minima, stated in",
        "`COVERAGE_TARGETS` so this table and the test that enforces them read",
        "the same numbers. Areas with no target are reported rather than bounded:",
        "the bank is not required to hold a given number of draft facts, but a",
        "reader of this report should be able to see how many there are.",
        "",
    ]
    if report["coverage_shortfalls"]:
        lines += ["**Unmet:**", ""]
        for group, (have, want) in sorted(report["coverage_shortfalls"].items()):
            lines.append(f"- `{group}` — {have} of {want}")
        lines.append("")
    lines += [
        "### Facts that expire",
        "",
    ]
    if report["perishable"]:
        lines += ["| Fact | Category | Serves until |", "|---|---|---|"]
        for entry in report["perishable"]:
            lines.append(
                f"| {entry['headline']} | `{entry['category']}` | {entry['valid_until']} |"
            )
    else:
        lines.append("None — nothing in the bank is a claim about the present.")
    lines += [
        "",
        "A fact about the present is served until its date and then never again,",
        "rather than served with a caveat. The build refuses any fact in a",
        "perishable category that carries no expiry.",
        "",
        "### Repeat-window audit",
        "",
        "| | |",
        "|---|---|",
        f"| Days examined | {repeat['days_examined']} |",
        f"| Distinct facts served | {repeat['distinct_facts_served']} |",
        f"| First repeat after | **{repeat['first_repeat_after_days']} days** |",
        f"| Schedule period | {rotation['period_days']} days |",
        f"| Consecutive same-category-group days | {rotation['consecutive_group_repeats']} |",
        f"| Same player or team inside {rotation['subject_window_days']} days | "
        f"{rotation['subject_repeats_within_window']} |",
        "",
        "Measured by serving the days and reading what came back, not by reasoning",
        "about the schedule. The consecutive-group figure is not zero and cannot",
        "be: near the end of a period only one lane has anything left in it, and a",
        "schedule that refused to place a fact there would have to drop it.",
        "",
        "### Duplicate audit",
        "",
        f"{report['duplicates']} candidates were rejected as duplicates or",
        "near-duplicates. Two facts are compared only when they are about the SAME",
        "subject — two different players saying a similar sentence are two facts,",
        "not one — and the comparison is on the headline, because the body carries",
        "shared explanatory boilerplate that would make every fact from one",
        "generator look like a copy of its siblings.",
        "",
        "### Facts per pattern",
        "",
        "| Pattern | Candidates | Published |",
        "|---|---|---|",
    ]
    for pattern, published in report["by_pattern"].items():
        produced = report["candidates_by_pattern"].get(pattern, published)
        lines.append(f"| `{pattern}` | {produced} | {published} |")

    if report["unused_categories"]:
        lines += [
            "",
            "### Categories with no published fact",
            "",
            "Named rather than hidden — each is a gap in the bank, not a category",
            "that does not exist.",
            "",
            "".join(f"- `{c}`\n" for c in report["unused_categories"]),
        ]

    lines += ["", "### Mean quality scores", "", "| Axis | Mean |", "|---|---|"]
    for axis, value in report["mean_scores"].items():
        lines.append(f"| {axis} | {value} |")

    lines += ["", "### The twenty strongest accepted facts", ""]
    for entry in report["strongest"]:
        lines.append(
            f"1. **{entry['headline']}** — *{entry['category']}, "
            f"{entry['provenance']}, {entry['total']}/35*"
        )
    lines += ["", "### The weakest accepted facts", ""]
    for entry in report["weakest"]:
        lines.append(
            f"- {entry['headline']} — *{entry['category']}, {entry['total']}/35*"
        )

    lines += ["", "### A sample of what was rejected", ""]
    for entry in report["rejected_examples"]:
        lines.append(f"- {entry['headline']} — `{entry['reason']}` ({entry['detail']})")
    # One trailing newline, not two. `git diff --check` reports "new blank line
    # at EOF" for the second, and a generated file that fails the repository's
    # own hygiene check on every regeneration is a permanent small lie in the
    # diff.
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=BANK_PATH, help="where to write the bank")
    parser.add_argument(
        "--report", type=Path, default=None, help="also write a markdown report here"
    )
    parser.add_argument(
        "--sample-date",
        default="2026-01-01",
        help="the date the rotation sample starts from. A FIXED default rather "
        "than today, so the report is reproducible instead of clock-dependent.",
    )
    args = parser.parse_args()

    # THE INPUTS, BEFORE ANY OF THEM IS READ.
    #
    # Named first so a packaging mistake reports itself as one. Without this,
    # a build missing `data/facts/` produced a perfectly valid 113-fact bank
    # and failed four steps later on the `MIN_FACTS` floor — a true statement
    # about a count, and no help at all in finding the cause.
    try:
        assert_inputs_present()
    except FileNotFoundError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    try:
        candidates = build_candidates()
        bank, rejected = build_bank()
    except EditorialFactError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if len(bank) < MIN_FACTS:
        print(
            f"ERROR: only {len(bank)} facts published, expected at least "
            f"{MIN_FACTS}. The schedule's period is exactly the size of the "
            "bank, so this floor IS the no-repeat guarantee — a daily feature "
            "must not cycle its whole inventory inside seven weeks.",
            file=sys.stderr,
        )
        return 1

    unknown = sorted({fact.category for fact in bank} - set(CATEGORIES))
    if unknown:
        print(f"ERROR: unknown categories {unknown}", file=sys.stderr)
        return 1

    unexpiring = [
        fact.fact_id
        for fact in bank
        if fact.category in PERISHABLE_CATEGORIES and not fact.valid_until
    ]
    if unexpiring:
        print(
            f"ERROR: {len(unexpiring)} fact(s) about the present carry no expiry "
            f"(first: {unexpiring[0]}).",
            file=sys.stderr,
        )
        return 1

    unsourced = [f.fact_id for f in bank if not f.source_detail or not f.verified]
    if unsourced:
        print(
            f"ERROR: {len(unsourced)} fact(s) are unsourced or unverified "
            f"(first: {unsourced[0]}). Every published fact names a source "
            "somebody checked.",
            file=sys.stderr,
        )
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        json.dumps(bank_payload(bank), indent=2, sort_keys=True, ensure_ascii=False)
        + "\n"
    )

    report = build_report(bank, rejected, candidates, args.sample_date)
    print(f"wrote {len(bank)} facts to {args.out}")
    print(f"  candidates {report['candidates']}, rejected {report['rejected']}")
    for category, count in report["by_category"].items():
        print(f"  {category:24s} {count}")

    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(_markdown(report))
        print(f"wrote the report to {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
