"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { getMethodology, getPeakWindowBoard, getSeasonBoard } from "@/lib/api";
import type { Methodology, RankingBoardData, RankingBoardId, RankingRow } from "@/types";
import RankingsTable, { ComponentLegend } from "@/components/rankings/RankingsTable";
import RankingsDetail from "@/components/rankings/RankingsDetail";
import ScoreExplainModal from "@/components/rankings/ScoreExplainModal";
import RankingsProvenance from "@/components/rankings/RankingsProvenance";
import {
  boardHeadingFor,
  boardShortLabelFor,
  explainerFor,
} from "@/components/rankings/board-copy";
import {
  DEFAULT_SORT_DIRECTION,
  DEFAULT_SORT_KEY,
  RANKING_COLUMNS,
  RANKING_COMPONENT_KEYS,
  hasComponents,
  isDefaultSort,
  sortRankingRows,
  type RankingSortKey,
  type SortDirection,
} from "@/components/rankings/board-model";

/**
 * `?sort=statistical_impact` (any `RankingComponentKey`, or `"total"`) —
 * the deep link the homepage's interactive component comparison uses so
 * "click a component" lands here already sorted by it, instead of on a
 * generic rankings page the visitor has to re-sort themselves. Reads once
 * on mount; the page's own sort controls own it from then on (this is a
 * starting point, not a synced URL state).
 *
 * Read via `window.location.search` in an effect, NOT `next/navigation`'s
 * `useSearchParams()` — the same choice `nav.tsx`'s `useLocationSearch`
 * already made and documents: that hook forces the nearest static shell
 * into a Suspense boundary, a real cost for a one-time initial read. This
 * page is already `"use client"`, so there is no server-render agreement
 * to protect; reading after mount is the same pattern, applied here too.
 */
function isDeepLinkableSortKey(value: string | null): value is RankingSortKey {
  return value === "total" || (RANKING_COMPONENT_KEYS as readonly string[]).includes(value ?? "");
}

function readSortFromLocation(): RankingSortKey | null {
  if (typeof window === "undefined") return null;
  const raw = new URLSearchParams(window.location.search).get("sort");
  return isDeepLinkableSortKey(raw) ? raw : null;
}

/**
 * PEAK3 Rankings.
 *
 * Phase 10B reduced this page from THREE boards to TWO. "Canonical Players"
 * answered the same question as Peak Windows -- one row per player, just over a
 * narrower universe -- so a reader had to diff two boards to tell them apart.
 * The canonical 250-pool leaderboards were NOT removed from the product: the
 * /api/v1/leaderboards route and its committed CSVs are untouched and the
 * methodology page still documents them.
 *
 * THE CONTRADICTION THIS FILE USED TO CARRY (fixed here)
 * ------------------------------------------------------
 * The comment above this one used to claim the two remaining boards "ask
 * genuinely different questions". At the 3-Year and 5-Year settings that is
 * true. At the 1-Year setting it is false, and provably so: a peak window of
 * length one IS a single season, so both boards return literally the same top
 * rows -- rank 1 Michael Jordan 1990-91 at 97.53, rank 2 LeBron James 2008-09
 * at 95.85, byte-identical row_ids in both generated artifacts. Meanwhile the
 * page header rendered "1-Year Peak Windows" directly beside a tab named
 * "Single Seasons": two names for one concept, presented as a choice between
 * two things. The blurb ("their single best consecutive stretch") was strained
 * at n=1 for the same reason -- a stretch of one.
 *
 * What is actually different at n=1 is de-duplication, and nothing else:
 *
 *   Peak Windows @ 1-Year -- best single season, ONE row per player
 *   Single Seasons        -- every qualifying season, repeats expected
 *
 * So the copy now says that, in those words, instead of implying a difference
 * of question where there is only a difference of grouping. At 3-Year and
 * 5-Year the boards genuinely do diverge and the copy says that too.
 * apps/api/tests/test_regression.py
 * ::test_the_two_boards_differ_only_by_deduplication_at_one_year holds the
 * claim true against the generated artifacts, so this copy cannot quietly
 * become wrong again.
 *
 * NOTE FOR FUTURE EDITORS: an existing e2e (gameplay.spec.ts:152) looks up a
 * *tab* by /3.year|3-year/i with NO tablist scoping, so exactly ONE control on
 * this page may match that wording. The window selector owns it
 * ("1-Year"/"3-Year"/"5-Year"); no board tab or sort control may use that
 * phrasing. Captions and prose are not controls and are unaffected.
 */

const BOARDS: { id: RankingBoardId; label: string; testId: string }[] = [
  { id: "peakWindows", label: "Peak Windows", testId: "pool-tab-peak-windows" },
  { id: "seasons", label: "Single Seasons", testId: "pool-tab-seasons" },
];

// Ascending window length, so the tab order matches the thing the tabs vary.
// 2-Year is a canonical board of its own (leaderboards/top_250_2_year_prime.csv,
// generated by peak3.n_year_windows with n=2), NOT a blend of the 1Y and 3Y
// boards -- a two-season peak has its own winner because the second season is
// weighted, not averaged in.
const WINDOW_OPTIONS: { id: "1y" | "2y" | "3y" | "5y"; label: string }[] = [
  { id: "1y", label: "1-Year" },
  { id: "2y", label: "2-Year" },
  { id: "3y", label: "3-Year" },
  { id: "5y", label: "5-Year" },
];


const PAGE_SIZE = 50;

export default function RankingsPage() {
  const [board, setBoard] = useState<RankingBoardId>("peakWindows");
  const [peakWindow, setPeakWindow] = useState<"1y" | "2y" | "3y" | "5y">("1y");
  const [search, setSearch] = useState("");
  const [debouncedSearch, setDebouncedSearch] = useState("");
  const [data, setData] = useState<RankingBoardData | null>(null);
  const [methodology, setMethodology] = useState<Methodology | null>(null);
  const [visible, setVisible] = useState(PAGE_SIZE);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [sortKey, setSortKey] = useState<RankingSortKey>(DEFAULT_SORT_KEY);
  const [sortDirection, setSortDirection] = useState<SortDirection>(DEFAULT_SORT_DIRECTION);
  const [openRow, setOpenRow] = useState<RankingRow | null>(null);
  // WHICH ROW THE DETAIL PANEL IS SHOWING. Held as a row_id rather than a row
  // object so a refetch (a different window, a new search) re-resolves it
  // against the live data instead of pinning a stale copy on screen.
  const [selectedRowId, setSelectedRowId] = useState<string | null>(null);

  useEffect(() => {
    const t = setTimeout(() => setDebouncedSearch(search.trim()), 250);
    return () => clearTimeout(t);
  }, [search]);

  // `?sort=<component>` deep link (the homepage's component comparison uses
  // this) — read once, on mount, so a visitor who arrives already sorted
  // can still freely change it afterward with the page's own controls.
  useEffect(() => {
    const requested = readSortFromLocation();
    if (!requested) return;
    setSortKey(requested);
    setSortDirection(RANKING_COLUMNS.find((c) => c.key === requested)?.initialDirection ?? "desc");
  }, []);

  // Component weights and long-form copy for the modal come from the real
  // methodology endpoint -- never hardcoded in TS (project rule).
  useEffect(() => {
    getMethodology()
      .then(setMethodology)
      .catch(() => setMethodology(null));
  }, []);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);
    const request =
      board === "peakWindows"
        ? getPeakWindowBoard(peakWindow, { limit: 1000, search: debouncedSearch })
        : getSeasonBoard({ limit: 1000, search: debouncedSearch });

    request
      .then((result) => {
        if (cancelled) return;
        setData(result);
        setVisible(PAGE_SIZE);
      })
      .catch(() => {
        if (!cancelled) {
          setData(null);
          setError("Could not load rankings. Is the API running?");
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [board, peakWindow, debouncedSearch]);

  // Switching board resets sort: a component sort silently carried across
  // boards would reorder a board the user has not looked at yet.
  const selectBoard = useCallback((next: RankingBoardId) => {
    setBoard(next);
    setSortKey(DEFAULT_SORT_KEY);
    setSortDirection(DEFAULT_SORT_DIRECTION);
    setSearch("");
    setDebouncedSearch("");
  }, []);

  const handleSort = useCallback((key: RankingSortKey) => {
    setSortKey((prevKey) => {
      const column = RANKING_COLUMNS.find((c) => c.key === key);
      const initial = column?.initialDirection ?? "desc";
      // Re-clicking the active column flips it; a new column starts at its own
      // natural direction (rank ascends, every score descends).
      setSortDirection((prevDirection) =>
        prevKey === key ? (prevDirection === "asc" ? "desc" : "asc") : initial
      );
      return key;
    });
  }, []);

  // Memoised so the `?? []` fallback doesn't mint a fresh array identity on
  // every render and invalidate the sort memo below.
  const rows = useMemo(() => data?.rows ?? [], [data]);
  const showComponents = hasComponents(rows);
  const sortedRows = useMemo(
    () => sortRankingRows(rows, sortKey, sortDirection),
    [rows, sortKey, sortDirection]
  );
  const shownRows = useMemo(() => sortedRows.slice(0, visible), [sortedRows, visible]);

  // THE TOP-RANKED ROW IS THE DEFAULT, resolved from the live rows every
  // render rather than latched on load. A board switch, a window switch or a
  // search all change what "the top row" means, and a detail panel still
  // showing the previous board's leader would be showing a row that is no
  // longer in the list beside it.
  const selectedRow = useMemo(() => {
    if (!sortedRows.length) return null;
    const match = selectedRowId
      ? sortedRows.find((row) => row.row_id === selectedRowId)
      : null;
    return match ?? sortedRows[0];
  }, [sortedRows, selectedRowId]);

  const boardHeading = boardHeadingFor(board, peakWindow);
  const boardLabel = boardShortLabelFor(board, peakWindow);
  const explainer = explainerFor(board, peakWindow);
  const sortColumn = RANKING_COLUMNS.find((c) => c.key === sortKey);
  const isSorted = !isDefaultSort(sortKey, sortDirection);

  return (
    <div className="min-h-screen px-4 py-8">
      <div className="mx-auto max-w-5xl flex flex-col gap-5">
        <header className="flex flex-col gap-1.5">
          <h1 className="font-display text-3xl font-bold" style={{ color: "var(--text-primary)" }}>
            PEAK3 Rankings
          </h1>
          <p className="text-sm max-w-2xl" style={{ color: "var(--text-secondary)" }}>
            Every score below is the official PEAK3 formula. Select any row to see exactly how it
            was built.
          </p>
        </header>

        {/* Board toggle. flex-wrap so a narrow viewport stacks instead of
            overflowing -- an @mobile e2e asserts no horizontal page overflow. */}
        <div className="flex flex-col gap-2">
          <div
            role="tablist"
            aria-label="Ranking board"
            className="flex flex-wrap gap-1.5 p-1 rounded-xl w-fit max-w-full"
            style={{ background: "var(--bg-surface)", border: "1px solid var(--border-subtle)" }}
          >
            {BOARDS.map((b) => {
              const active = b.id === board;
              return (
                <button
                  key={b.id}
                  role="tab"
                  aria-selected={active}
                  data-testid={b.testId}
                  onClick={() => selectBoard(b.id)}
                  className="text-xs font-semibold uppercase tracking-wide rounded-lg px-3.5 py-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus-ring)]"
                  style={
                    active
                      ? { background: "var(--peak-accent, #f5c842)", color: "var(--text-inverse)" }
                      : { background: "transparent", color: "var(--text-secondary)" }
                  }
                >
                  {b.label}
                </button>
              );
            })}
          </div>
          {/* Body-size, --text-secondary: this sentence is the only thing that
              distinguishes the two boards at the 1-Year setting, so it cannot
              be 12 px muted filler. */}
          <p className="rankings-explainer" data-testid="pool-explainer">
            {explainer}
          </p>
        </div>

        {/* Window duration -- Peak Windows only. */}
        {board === "peakWindows" && (
          <div role="tablist" aria-label="Peak window duration" className="flex flex-wrap gap-1.5">
            {WINDOW_OPTIONS.map((w) => {
              const active = w.id === peakWindow;
              return (
                <button
                  key={w.id}
                  role="tab"
                  aria-selected={active}
                  data-testid={`peak-window-tab-${w.id}`}
                  onClick={() => setPeakWindow(w.id)}
                  className="text-xs font-semibold rounded-full px-3 py-1.5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus-ring)]"
                  style={
                    active
                      ? {
                          background: "var(--peak-accent-bg, rgba(245,200,66,0.12))",
                          color: "var(--peak-accent-text, #f5c842)",
                          border: "1px solid var(--peak-accent-dim)",
                        }
                      : {
                          background: "var(--bg-surface)",
                          color: "var(--text-secondary)",
                          border: "1px solid var(--border-subtle)",
                        }
                  }
                >
                  {w.label}
                </button>
              );
            })}
          </div>
        )}

        <div className="flex flex-col sm:flex-row sm:items-center gap-2">
          <input
            type="search"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder={board === "seasons" ? "Search players or seasons…" : "Search players…"}
            aria-label="Search rankings"
            data-testid="rankings-search"
            className="flex-1 rounded-lg px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus-ring)]"
            style={{
              background: "var(--bg-surface)",
              color: "var(--text-primary)",
              border: "1px solid var(--border-default)",
            }}
          />
          {isSorted && sortColumn && (
            <div
              className="flex items-center gap-2 text-xs shrink-0"
              data-testid="active-sort-note"
              style={{ color: "var(--text-secondary)" }}
            >
              <span>
                Sorted by{" "}
                <strong style={{ color: "var(--peak-accent-text, #f5c842)" }}>{sortColumn.full}</strong>{" "}
                {sortDirection === "desc" ? "high to low" : "low to high"}
              </span>
              <button
                onClick={() => {
                  setSortKey(DEFAULT_SORT_KEY);
                  setSortDirection(DEFAULT_SORT_DIRECTION);
                }}
                data-testid="reset-sort-btn"
                className="font-semibold uppercase tracking-wide rounded px-2 py-1 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus-ring)]"
                style={{
                  background: "var(--bg-surface)",
                  color: "var(--text-secondary)",
                  border: "1px solid var(--border-default)",
                }}
              >
                Reset
              </button>
            </div>
          )}
        </div>

        {showComponents && <ComponentLegend />}

        {error && (
          <div
            role="alert"
            data-testid="rankings-error"
            className="rounded-lg p-4 text-sm text-center"
            style={{ background: "var(--bg-surface)", color: "var(--incorrect)" }}
          >
            {error}
          </div>
        )}

        {loading && !data && (
          <div
            className="rounded-lg p-6 text-sm text-center"
            style={{ background: "var(--bg-surface)", color: "var(--text-muted)" }}
          >
            Loading rankings…
          </div>
        )}

        {data && (
          <>
            {/* The board says what it is, in the same words as the explainer
                above it. Previously this read "1-Year Peak Windows" while the
                tab beside it read "Single Seasons" -- two names for one
                concept, side by side. */}
            <h2 className="rankings-board-heading" data-testid="rankings-board-heading">
              {boardHeading}
            </h2>
            <div className="rankings-split">
              <div className="rankings-split-list">
            <RankingsTable
              rows={shownRows}
              sortKey={sortKey}
              sortDirection={sortDirection}
              onSort={handleSort}
              showComponents={showComponents}
              onOpenRow={setOpenRow}
              caption={`${boardHeading} — ranked by PEAK3 score. Select a row to see how the score was built.`}
              emptyMessage={
                debouncedSearch
                  ? `No rows match “${debouncedSearch}”.`
                  : "No rows available for this board."
              }
              labelHeading={board === "seasons" ? "Season" : "Window"}
              selectedRowId={selectedRow?.row_id ?? null}
              onSelectRow={(row) => setSelectedRowId(row.row_id)}
            />
              </div>
              <div className="rankings-split-detail">
                <RankingsDetail
                  row={selectedRow}
                  boardLabel={boardLabel}
                  windowLabel={board === "peakWindows" ? peakWindow.toUpperCase() : null}
                  populationNoun={board === "seasons" ? "scored season" : "peak window"}
                  onExplain={setOpenRow}
                />
              </div>
            </div>

            {sortedRows.length > shownRows.length && (
              <button
                onClick={() => setVisible((v) => v + PAGE_SIZE)}
                data-testid="rankings-show-more"
                className="self-center text-xs font-semibold uppercase tracking-wide rounded px-4 py-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus-ring)]"
                style={{
                  background: "var(--bg-surface)",
                  color: "var(--text-secondary)",
                  border: "1px solid var(--border-default)",
                }}
              >
                Show more ({shownRows.length} of {sortedRows.length})
              </button>
            )}

            {/* Provenance. Still last on the page, no longer 10 px grey --
                see RankingsProvenance for why the serving-gate note in
                particular had to stop being unreadable. */}
            <RankingsProvenance meta={data.meta} fallbackRowCount={rows.length} />
          </>
        )}
      </div>

      <ScoreExplainModal
        row={openRow}
        board={board}
        boardLabel={boardLabel}
        boardRowCount={data?.meta.total_available ?? rows.length}
        populationNoun={board === "seasons" ? "scored seasons" : "peak windows"}
        methodology={methodology}
        onClose={() => setOpenRow(null)}
      />
    </div>
  );
}
